name: Zotero to Readwise Automation

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4,16 * * *" # Runs at 03:00 AM (UTC) every day (Check https://crontab.guru/)

jobs:
  zotero-to-readwise-automation:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🐍 Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 💿 Install dependencies
        run: pip install setuptools

      - name: 💿 Install Zotero2Readwise Python package
        run: pip install ./zotero2readwise

      - name: 🚀 Run Automation
        run: python zotero2readwise/run.py ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}

      - name: 🔎 Report Failures
        run: python report_failures.py
